# Generated by Django 5.0.4 on 2024-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', help_text='Выберите роль пользователя', max_length=20, verbose_name='Роль пользователя')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Пользователь-сотрудник')),
                ('is_active', models.BooleanField(default=True, help_text='Укажите, активен ли аккаунт', verbose_name='Аккаунт активен')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id'],
            },
        ),
    ]
